import { createSlice } from "@reduxjs/toolkit";
import { IUser } from "../../../types/User";

const initialState: Array<IUser> = [
  {
    id: 2,
    description: "",
    phone: "+79281234567",
    username: "User 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    comments: [],
    adverts: [],
  },
  {
    id: 3,
    description: "",
    phone: "+79281234568",
    username: "User 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 4,
    description: "",
    phone: "+79282234569",
    username: "User 3",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 5,
    description: "",
    phone: "+79283234567",
    username: "User 4",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 6,
    description: "",
    phone: "+79631234567",
    username: "Usr 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 7,
    description: "",
    phone: "+79331234567",
    username: "Usr 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 8,
    description: "",
    phone: "+79281334567",
    username: "Usr 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 9,
    description: "",
    phone: "+79281334568",
    username: "User 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 10,
    description: "",
    phone: "+79282334569",
    username: "Use 0",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 11,
    description: "",
    phone: "+79283334567",
    username: "User 4",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 12,
    description: "",
    phone: "+79631334567",
    username: "Usr 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
  {
    id: 13,
    description: "",
    phone: "+79331334567",
    username: "Usr 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    likes: [],
    adverts: [],
    comments: [],
  },
];

export const usersSlice = createSlice({
  name: "users",
  initialState,
  reducers: {},
});
