export const GREY_LIGHT = '#F3F3F5';
export const GREY_MIDDLE = '#DDDDDD';
export const GREY_DARK = '#999999'
export const WHITE = '#FFFFFF';
export const BLACK_LIGHT = '#202026';
export const BLACK_LIGHT_OPACITY = 'rgba(0, 0, 0, 0.2)';
export const BLACK_DARK = '#000000';
export const BLUE = '#007AFF';
export const RED = '#FF3B30';
export const YELLOW = '#FFCC00';
export const GREEN = '#34C759';