import { IUser } from "../types/User";

export const USER: IUser = {
  id: "1",
  phone: "+7 928 123-45-67",
  username: "ДунСтрой Групп",
  email: "email@mail.ru",
  description: "Описание к аккаунту",
  rating: 4.7,
  ratesCount: 12,
  comments: [
    {
      id: "1",
      authorId: "1",
      authorName: "ДунСтрой Групп",
      adresseeId: "2",
      rate: 5,
      text: "В данном блоке будет отображаться текст вашего отзыва",
    },
    {
      id: "2",
      authorId: "1",
      authorName: "ДунСтрой Групп",
      adresseeId: "2",
      rate: 5,
      text: "В данном блоке будет отображаться текст вашего отзыва",
    },
    {
      id: "3",
      authorId: "1",
      authorName: "ДунСтрой Групп",
      adresseeId: "3",
      rate: 5,
      text: "В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва.",
    },
    {
      id: "4",
      authorId: "1",
      authorName: "ДунСтрой Групп",
      adresseeId: "5",
      rate: 5,
      text: "В данном блоке будет отображаться текст вашего отзыва",
    },
    {
      id: "5",
      authorId: "2",
      authorName: "Илья Ильин",
      adresseeId: "1",
      rate: 5,
      text: "В данном блоке будет отображаться текст отзыва пользователя о вас",
    },
  ],
  adverts: [
    {
      id: "0",
      userId: "1",
      username: "ДунСтрой Групп",
      userRating: 4.7,
      type: "technic",
      updatedAt: Date.now(),
      likes: ["1", "2", "3", "7"],
      views: ["1", "2", "3", "4", "5", "6", "7"],
      title: "Сдаётся гусеничный экскаватор Hyundai",
      general: {
        address: "Москва, Химки",
        count: 3,
        workMode: "День",
        distance: 22,
        comment:
          "В данном блоке будет отображаться комментарий пользователя. Комментарий может содержать до 400 символов.",
        rentalPeriod: {
          from: new Date("2023-11-23").valueOf(),
          to: new Date("2023-12-23").valueOf(),
        },
        rentalDaysCount:
          new Date("2023-11-23").valueOf() -
          new Date("2023-12-23").valueOf() / (1000 * 3600 * 24),
      },
      price: {
        price: 10000,
        paymentFor: "Смену",
        paymentType: "Любой",
      },
      params: {
        photos: [
          "https://stroy-plys.ru/uploads/posts/2014-01/1390641675_ekskavator-gusenichnyy-hyundai-380.jpg",
          "https://cdn.stpulscen.ru/system/ckeditor_assets/pictures/352723/content_kovshi-jcb-01.jpg",
          "https://avatars.mds.yandex.net/get-autoru-vos/11038141/883df25017df09a8cda4c1a43d9161e9/1200x900",
        ],
        mainParams: {
          technicType: "Экскаватор гусеничный",
          mark: "Hyundai",
          model: "JCB",
          productionYear: "2021",
        },
        otherParams: {
          weight: 32.2,
          volume: 1.44,
        },
      },
    },
  ],
};

export const USERS_LIST: Array<IUser> = [
  {
    id: "2",
    description: "",
    phone: "+7 928 123-45-67",
    username: "User 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    comments: [],
    adverts: [
      {
        id: "1",
        userId: "2",
        username: "User 1",
        userRating: 3.7,
        type: "technic",
        updatedAt: Date.now() - 1000 * 3600,
        likes: ["2", "3", "7", "13"],
        views: ["1", "2", "3", "4", "5", "6", "7"],
        title: "Сдаётся гусеничный экскаватор Hyundai",
        general: {
          address: "Москва, Химки",
          count: 3,
          workMode: "День",
          rentalPeriod: {
            from: new Date("2023-11-23").valueOf(),
            to: new Date("2023-12-23").valueOf(),
          },
          rentalDaysCount:
            new Date("2023-11-23").valueOf() -
            new Date("2023-12-23").valueOf() / (1000 * 3600 * 24),
        },
        price: {
          price: 10000,
          paymentFor: "Смену",
          paymentType: "Наличные",
        },
        params: {
          mainParams: {
            technicType: "Экскаватор гусеничный",
            mark: "Hyundai",
            productionYear: '2021',
          },
          photos: [
            "https://cdn.stpulscen.ru/system/ckeditor_assets/pictures/352723/content_kovshi-jcb-01.jpg",
            "https://avatars.mds.yandex.net/get-autoru-vos/11038141/883df25017df09a8cda4c1a43d9161e9/1200x900",
            "https://stkalmaz.ru/wp-content/uploads/2023/03/7086387da2a68ceebf759ef9b1eac6f3.jpeg",
            "https://www.prostanki.com/img/boardpics/2020_03/A1BynE6lzoSMcp9Qs3Jq.jpg",
            "http://static.gmstar.ru/boardImage/imageOriginal/4/115921/1536652020_gusenichnyy_ekskavat.jpg",
            "https://www.tornometal.com/wp-content/uploads/2015/04/JS205LC-Low2.jpg",
            "https://avatars.mds.yandex.net/get-ydo/3904573/2a000001874673c75e8aa2bbbceda3077e5b/diploma",
            "https://vst-parts.ru/wa-data/public/shop/products/45/07/745/images/923/923.970.jpg",
            "https://stroy-plys.ru/uploads/posts/2014-01/1390641675_ekskavator-gusenichnyy-hyundai-380.jpg",
          ],
          otherParams: {
            weight: 32.2,
            volume: 1.44,
          },
        },
      },
    ],
  },
  {
    id: "3",
    description: "",
    phone: "+7 928 123-45-68",
    username: "User 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [
      {
        id: "3",
        authorId: "1",
        authorName: "ДунСтрой Групп",
        adresseeId: "3",
        rate: 5,
        text: "В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва. В данном блоке будет отображаться текст вашего отзыва.",
      },
      {
        id: "6",
        authorId: "2",
        authorName: "User 1",
        adresseeId: "3",
        rate: 3,
        text: "В данном блоке будет отображаться текст вашего отзыва",
      },
      {
        id: "7",
        authorId: "4",
        authorName: "User 3",
        adresseeId: "3",
        rate: 4,
        text: "В данном блоке будет отображаться текст вашего отзыва",
      },
    ],
  },
  {
    id: "4",
    description: "",
    phone: "+7 928 223-45-69",
    username: "User 3",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [
      {
        id: "7",
        authorId: "4",
        authorName: "ДунСтрой Групп",
        adresseeId: "3",
        rate: 5,
        text: "В данном блоке будет отображаться текст вашего отзыва",
      },
    ],
  },
  {
    id: "5",
    description: "",
    phone: "+7 928 323-45-67",
    username: "User 4",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [
      {
        id: "8",
        authorId: "5",
        authorName: "ДунСтрой Групп",
        adresseeId: "3",
        rate: 5,
        text: "В данном блоке будет отображаться текст вашего отзыва",
      },
    ],
  },
  {
    id: "6",
    description: "",
    phone: "+7 963 123-45-67",
    username: "Usr 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  {
    id: "7",
    description: "",
    phone: "+7 933 123-45-67",
    username: "Usr 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [
      {
        id: "9",
        authorId: "7",
        authorName: "ДунСтрой Групп",
        adresseeId: "3",
        rate: 5,
        text: "В данном блоке будет отображаться текст вашего отзыва",
      },
    ],
  },
  {
    id: "8",
    description: "",
    phone: "+7 928 133-45-67",
    username: "Usr 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  {
    id: "9",
    description: "",
    phone: "+7 928 133-45-68",
    username: "User 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  {
    id: "10",
    description: "",
    phone: "+7 928 233-45-69",
    username: "Use 0",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  {
    id: "11",
    description: "",
    phone: "+7 928 333-45-67",
    username: "User 4",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  {
    id: "12",
    description: "",
    phone: "+7 963 133-45-67",
    username: "Usr 2",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  {
    id: "13",
    description: "",
    phone: "+7 933 133-45-67",
    username: "Usr 1",
    email: "test@mail.ru",
    rating: 3.7,
    ratesCount: 12,
    adverts: [],
    comments: [],
  },
  USER,
];
